### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by BrittSzynal** [thinkshout/thinkshout#738] opened 2019-03-05 22:49 UTC
## Overview
 
- [x] Add updated About Us language above our team on this page: https://ntc2019--thinkshout.netlify.com/team/

This essentially combines the team and values page from the current site: https://thinkshout.com/values/ 

## Links
Updated language: https://docs.google.com/document/d/1KHmcdt2xam9yi68c_oe5Wk5O5pFSPC4zv8SHtCCkN34/edit

**Comment by komejo** [comment] 2019-03-06 22:54
https://ntc2019--thinkshout.netlify.com/about/

**Comment by ThomasKing** [comment] 2019-03-07 01:02
Reviewing now. This page will need some content update and styling as well. Will talk w/ @vickibrown about the best way to get this done using existing styles.

**Comment by brittstetson** [comment] 2019-03-07 18:16
@ThomasKing any feedback here before we pass on to Lev? What are feelings about how much content on the page? Do we need to adjust style or break into 2 pages?

**Comment by ThomasKing** [comment] 2019-03-07 19:32
@brittstetson Vicki is doing a simple design update that will include page titles and reduce the copy. That's coming next.

**Comment by vickibrown** [comment] 2019-03-07 21:19
@brittstetson @komejo here's the invision link for good measure. https://thinkshout.invisionapp.com/share/F3QCZY3ZBDW#/350967097_About_Desktop

**Comment by ThomasKing** [comment] 2019-03-08 03:48
@brittstetson I realize that the copy on About and Home is very similar. Will work with Chelsea's copy to find the correct line to differentiate these pages.

**Comment by vickibrown** [comment] 2019-03-08 21:44
@komejo can you replace the image behind the black section on this page with this? https://drive.google.com/file/d/1xqg-Edj2kCSkhuMOgzBuX2mZKgyh8Z3i/view

**Comment by chelseamaricle** [comment] 2019-03-08 23:42
@komejo I want to make sure you saw Vicki's comment above ^ as the ticket didn't get assigned to you. Can you also replace the headline copy "We partner with courageous organizations whose missions inspire our team and whose impact defines our work." with the following?

We are committed to advancing the causes we love.

**Comment by brittstetson** [comment] 2019-03-09 00:16
@komejo see latest two comments

**Comment by komejo** [comment] 2019-03-09 01:35
Ready for review: https://ntc2019--thinkshout.netlify.com/about/

**Closed** 2023-07-24 20:08 UTC
Labels: Content
