### ISSUE TITLE
Changing categories breaks blog page

### ISSUE THREAD

**Issue by levelos** [thinkshout/thinkshout#331] opened 2016-03-08 16:37 UTC
All of the blog posts not in the selected category show unformatted at the bottom of the page.

**Comment by komejo** [comment] 2016-03-08 17:57
This was being caused by `blog_teaser.html` placing an extra closing div tag on the page when an author was not in `/data/team.yml` (Candice!). Fixed.

**Closed by komejo** 2016-03-08 17:57 UTC
